FROM debian:bullseye-slim

WORKDIR /usr/local/lib/mlshapes/
RUN apt update && apt -y upgrade 
RUN apt install -y build-essential libssl-dev python3-dev python3 \
python3-pip python3-venv 

COPY . /usr/local/lib/zmqtracker

RUN pip3 install install opencv-contrib-python-headless \
websockets imutils rpyc imagezmq gputil paho-mqtt
    
CMD "/usr/local/lib/zmqtracker/docker-osx.sh" 

